#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

UBUNTU_DISTRO="${UBUNTU_DISTRO:-ubuntu}"
GATEWAY_PORT="${GATEWAY_PORT:-18789}"
GATEWAY_BIND="${GATEWAY_BIND:-loopback}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PLUGIN_DIR="${REPO_ROOT}/openclaw-plugin-mobile-ui"

# ---- choose droidrun provider/model in Termux, then pass to Ubuntu via temp env ----
TMP_ENV="${TMPDIR:-/data/data/com.termux/files/usr/tmp}/clawmobile-env.$$.sh"
trap 'rm -f "$TMP_ENV"' EXIT

DROIDRUN_PROVIDER_CHOSEN="${DROIDRUN_PROVIDER:-}"
DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL:-}"

pick_llm_termux() {
  # user override wins
  if [ -n "${DROIDRUN_PROVIDER_CHOSEN}" ] && [ -n "${DROIDRUN_MODEL_CHOSEN}" ]; then
    return 0
  fi

  # order: Gemini -> OpenAI -> Anthropic -> DeepSeek (Ollama handled in Ubuntu if needed)
  if [ -n "${GEMINI_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="Gemini"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-gemini-2.5-flash}"
    return 0
  fi

  if [ -n "${OPENAI_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="OpenAI"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-gpt-5.2}"
    return 0
  fi

  if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="Anthropic"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-claude-opus-4-6}"
    return 0
  fi

  if [ -n "${DEEPSEEK_API_KEY:-}" ]; then
    DROIDRUN_PROVIDER_CHOSEN="DeepSeek"
    DROIDRUN_MODEL_CHOSEN="${DROIDRUN_MODEL_CHOSEN:-deepseek-reasoner}"
    return 0
  fi

  return 1
}

if pick_llm_termux; then
  echo "[run] picked droidrun llm in termux: provider=${DROIDRUN_PROVIDER_CHOSEN} model=${DROIDRUN_MODEL_CHOSEN}"
else
  echo "[run] WARNING: no LLM key found in Termux env. Set one of GEMINI_API_KEY/OPENAI_API_KEY/ANTHROPIC_API_KEY/DEEPSEEK_API_KEY."
fi

# Write ONLY chosen provider/model + the one required API key to TMP_ENV
{
  echo "# generated by run.sh"

  if [ -n "${DROIDRUN_PROVIDER_CHOSEN:-}" ] && [ -n "${DROIDRUN_MODEL_CHOSEN:-}" ]; then
    printf "export DROIDRUN_PROVIDER=%q\n" "${DROIDRUN_PROVIDER_CHOSEN}"
    printf "export DROIDRUN_MODEL=%q\n" "${DROIDRUN_MODEL_CHOSEN}"
  fi

  case "${DROIDRUN_PROVIDER_CHOSEN:-}" in
    Gemini)    [ -n "${GEMINI_API_KEY:-}" ] && printf "export GEMINI_API_KEY=%q\n" "$GEMINI_API_KEY" ;;
    OpenAI)    [ -n "${OPENAI_API_KEY:-}" ] && printf "export OPENAI_API_KEY=%q\n" "$OPENAI_API_KEY" ;;
    Anthropic) [ -n "${ANTHROPIC_API_KEY:-}" ] && printf "export ANTHROPIC_API_KEY=%q\n" "$ANTHROPIC_API_KEY" ;;
    DeepSeek)  [ -n "${DEEPSEEK_API_KEY:-}" ] && printf "export DEEPSEEK_API_KEY=%q\n" "$DEEPSEEK_API_KEY" ;;
  esac
} > "$TMP_ENV"

echo "[clawmobile] Starting OpenClaw Gateway..."
proot-distro login "${UBUNTU_DISTRO}" --shared-tmp -- bash -lc 'bash -seuo pipefail' <<EOF
REPO_ROOT='${REPO_ROOT}'
PLUGIN_DIR='${PLUGIN_DIR}'
TMP_ENV='${TMP_ENV}'

# ---- import chosen droidrun provider/model + key ----
if [ -f "\$TMP_ENV" ]; then
  # shellcheck disable=SC1090
  source "\$TMP_ENV"
fi

echo "[run] droidrun chosen: provider=\${DROIDRUN_PROVIDER:-<empty>} model=\${DROIDRUN_MODEL:-<empty>}"
echo "[run] key check: OPENAI_API_KEY=\${OPENAI_API_KEY:+<set>} GEMINI_API_KEY=\${GEMINI_API_KEY:+<set>} ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY:+<set>} DEEPSEEK_API_KEY=\${DEEPSEEK_API_KEY:+<set>}"

cd "\$REPO_ROOT"

# ---- ensure env.sh patch also loads (node netif patch) ----
if [ -f installer/ubuntu/env.sh ]; then
  # shellcheck disable=SC1091
  source installer/ubuntu/env.sh
fi

# ---- activate python virtual environment + pin CLAW_MOBILE_PYTHON ----
VENV_DIR=""
if [ -f "/root/venvs/clawmobile/bin/activate" ]; then
  VENV_DIR="/root/venvs/clawmobile"
elif [ -f "/root/venvs/clawbot/bin/activate" ]; then
  VENV_DIR="/root/venvs/clawbot"
fi

if [ -n "\$VENV_DIR" ]; then
  # shellcheck disable=SC1091
  source "\$VENV_DIR/bin/activate"
  if [ -x "\$VENV_DIR/bin/python3" ]; then
    export CLAW_MOBILE_PYTHON="\$VENV_DIR/bin/python3"
  else
    export CLAW_MOBILE_PYTHON="\$VENV_DIR/bin/python"
  fi
else
  echo "[run] WARNING: venv not found at /root/venvs/clawmobile or /root/venvs/clawbot; tools may use system python"
fi
echo "[run] CLAW_MOBILE_PYTHON=\${CLAW_MOBILE_PYTHON:-}" || true

# ---- ADB prep: pick a usable device serial automatically (prefer tcpip with port 5555) ----
if command -v adb >/dev/null 2>&1; then
  adb start-server >/dev/null 2>&1 || true
  mapfile -t DEVICES < <(adb devices | awk 'NR>1 && \$2=="device" {print \$1}')

  if [ "\${#DEVICES[@]}" -eq 0 ]; then
    echo "[run] WARNING: no adb device in 'device' state."
    echo "[run] adb devices output:"
    adb devices || true
    echo "[run] If unauthorized: enable USB/Wireless debugging and accept prompt on phone."
  else
    if [ -z "\${DROIDRUN_SERIAL:-}" ]; then
      PICK=""
      for s in "\${DEVICES[@]}"; do
        if [[ "\$s" == 127.0.0.1:5555 ]]; then
          PICK="\$s"
          break
        fi
      done
      [ -n "\$PICK" ] || PICK="\${DEVICES[0]}"
      export DROIDRUN_SERIAL="\$PICK"
    fi
    export ANDROID_SERIAL="\$DROIDRUN_SERIAL"
    echo "[run] adb selected serial: \${DROIDRUN_SERIAL}"
  fi
else
  echo "[run] WARNING: adb not found."
fi

# ---- build plugin if needed, then plugins install ----
if [ -d "\$PLUGIN_DIR" ]; then
  NEED_BUILD=0

  if [ ! -f "\$PLUGIN_DIR/dist/index.js" ] || [ ! -f "\$PLUGIN_DIR/dist/pyexec/android_exec.py" ]; then
    NEED_BUILD=1
    echo "[run] building plugin (dist output missing)..."
  elif [ "\$PLUGIN_DIR/package.json" -nt "\$PLUGIN_DIR/dist/index.js" ] || [ "\$PLUGIN_DIR/tsconfig.json" -nt "\$PLUGIN_DIR/dist/index.js" ]; then
    NEED_BUILD=1
    echo "[run] building plugin (package or tsconfig changed)..."
  elif [ -n "\$(find "\$PLUGIN_DIR/src" "\$PLUGIN_DIR/pyexec" "\$PLUGIN_DIR/scripts" -type f -newer "\$PLUGIN_DIR/dist/index.js" -print -quit 2>/dev/null || true)" ]; then
    NEED_BUILD=1
    echo "[run] building plugin (source newer than dist)..."
  fi

  if [ "\$NEED_BUILD" -eq 1 ]; then
    cd "\$PLUGIN_DIR"
    npm install
    npm run build
    cd "\$REPO_ROOT"
  fi

  echo "[run] openclaw plugins install \$PLUGIN_DIR"
  openclaw plugins install "\$PLUGIN_DIR" || true
else
  echo "[run] WARNING: plugin dir not found at \$PLUGIN_DIR"
fi

# ---- workspace seed: inject AGENTS/TOOLS blocks + sync skills ----
WORKSPACE="\$(openclaw config get agents.defaults.workspace 2>/dev/null | tr -d '\"' || true)"
[ -n "\$WORKSPACE" ] || WORKSPACE="/root/.openclaw/workspace"
mkdir -p "\$WORKSPACE"

SEED_DIR="\$REPO_ROOT/installer/workspace-seed"

append_block_if_missing() {
  local target="\$1"
  local block="\$2"
  local marker="CLAWMOBILE_BEGIN"

  [ -f "\$block" ] || return 0
  touch "\$target"

  if ! grep -q "\$marker" "\$target"; then
    printf "\n\n" >> "\$target"
    cat "\$block" >> "\$target"
    printf "\n" >> "\$target"
    echo "[run] injected mobile block into \$(basename "\$target")"
  else
    echo "[run] mobile block already present in \$(basename "\$target")"
  fi
}

append_block_if_missing "\$WORKSPACE/AGENTS.md" "\$SEED_DIR/AGENTS.mobile.md"
append_block_if_missing "\$WORKSPACE/TOOLS.md"  "\$SEED_DIR/TOOLS.mobile.md"

SKILLS_SRC="\$SEED_DIR/skills"
SKILLS_DST="\$WORKSPACE"

if [ -d "\$SKILLS_SRC" ]; then
  if ! rsync -a "\$SKILLS_SRC" "\$SKILLS_DST/"; then
    echo "[run] ERROR: failed to sync skills from \$SKILLS_SRC to \$SKILLS_DST -- gateway will not start" >&2
    exit 1
  fi
  echo "[run] synced skills -> \$SKILLS_DST"
else
  echo "[run] WARNING: seed skills not found at \$SKILLS_SRC/"
fi

# Add an extra command for Telegram to restore the IME (input method editor).
openclaw config set channels.telegram.customCommands '[{"command":"ime","description":"Restore the keyboard (IME)"}]'

openclaw config set tools.profile full

exec openclaw gateway --bind ${GATEWAY_BIND} --port ${GATEWAY_PORT} --verbose
EOF
